"""A re-run of step 27 must not delete a secret it does not know the name of.

`step_secrets` rebuilds /etc/sentinel/secrets.env from scratch on every run. It
used to fill the new file from two hard-coded lists — five operator keys and two
generated ones — and dropped everything else on the floor.

The host has eight keys. `SENTINEL_BEACON_SECRET` is the shared HMAC key between
Sentinel and the external watcher; it was added by hand after those lists were
written, it is not in secrets/.env.local, and it must never be regenerated
because the watcher holds the same value. So the documented password rotation,
`--force-step 22,27`, would have destroyed the only copy of it.

And nothing would have said so. This step prints a green line about the keys it
DID keep; `sentinel-beacon` exits 0 when the secret is missing, so `systemctl
restart` returns 0 and step 36 reports "enabled and restarted" over a dead unit.
The witness that exists to notice Sentinel's death would have gone quiet during
the procedure written to be safe.

These tests run the SHIPPED step 27 — declarations, `existing_secret` and
`step_secrets`, extracted verbatim between the `# --- 27` and `# --- 28` markers
— against a fabricated copy of the host's real key set.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
from pathlib import Path

import pytest

pytestmark = pytest.mark.security

REPO = Path(__file__).resolve().parents[2]
INSTALL_SH = REPO / "deploy" / "install.sh"
BASH = shutil.which("bash")

pytestmark = [pytest.mark.security,
              pytest.mark.skipif(BASH is None, reason="no bash on PATH")]

# The eight keys on the host. What matters is the NAMES — one of them is outside
# both of the installer's lists.
#
# The values are deliberately shaped so they cannot be mistaken for the real
# thing: test_repo_is_sanitised.py greps the whole tree for key-shaped strings,
# and a fixture that looks like an Anthropic key is exactly as much of a problem
# as a real one, because nobody triaging that finding can tell from the grep.
HOST_SECRETS = {
    "ANTHROPIC_API_KEY": "value-of-the-anthropic-key",
    "TELEGRAM_BOT_TOKEN": "value-of-the-bot-token",
    "TELEGRAM_CHAT_ID": "123456789",
    "SENTINEL_DB_PASSWORD": "OLD-db-password",
    "TELEGRAM_APPLY_PIN": "4242",
    "TELEGRAM_CALLBACK_HMAC_KEY": "a" * 64,
    "SENTINEL_SESSION_SECRET": "b" * 64,
    "SENTINEL_BEACON_SECRET": "c" * 64,
}


def step27_source() -> str:
    """Step 27 as shipped, not a copy of it.

    Extracted between the numbered section markers so the declarations travel
    with the functions. If the markers move, this raises rather than silently
    testing an empty string.
    """
    text = INSTALL_SH.read_text(encoding="utf-8")
    match = re.search(r"^# --- 27 -+\n(.*?)^# --- 28 -+$", text, re.S | re.M)
    assert match, "cannot find the step 27 block in install.sh"
    body = match.group(1)
    assert "step_secrets()" in body and "GENERATED_SECRET_KEYS" in body
    return body


HARNESS = """
source ./lib/common.sh
{step27}

# chown/chmod are stubbed: there is no `sentinel` user on a developer machine
# and modes do not survive this filesystem. The chmod stub records the SIZE of
# the file it is called on, which is what makes the ordering property testable:
# the mode has to be set while the file is still empty. Everything else here is
# the shipped code.
chown() {{ printf 'chown %s\\n' "$*" >> "$CALLS"; }}
chmod() {{ printf 'chmod %s size=%s\\n' "$*" "$(wc -c < "$2" 2>/dev/null || echo -1)" >> "$CALLS"; }}

# openssl is stubbed so that generation is OBSERVABLE. Asserting a value did not
# change is weaker than asserting no new one was ever minted.
#
# `rand -hex 32` mints a SECRET and must never happen when the host already has
# one; `rand -hex 16` mints the instance id, which step 27 does create on a
# fresh host by design. So the assertions below name the width rather than the
# binary, and this stub answers -hex 16 with something of the right SHAPE —
# `ensure_instance_id` re-reads the file and refuses anything else, and a stub
# that returned the placeholder for both would abort the step with a fatal
# error about the wrong thing.
openssl() {{
    printf 'openssl %s\\n' "$*" >> "$CALLS"
    if [[ "$*" == "rand -hex 16" ]]; then printf '0123456789abcdef0123456789abcdef'
    else printf 'FRESHLY-GENERATED'; fi
}}

declare -A SECRETS=({stdin})
step_secrets
"""


def run_step_secrets(tmp_path: Path, on_disk: dict[str, str] | None,
                     stdin: dict[str, str], extra_lines: str = "") -> dict:
    cfg = tmp_path / "etc"
    cfg.mkdir(parents=True, exist_ok=True)
    target = cfg / "secrets.env"
    if on_disk is not None:
        body = "# Generated by install.sh at 2026-07-31T00:00:00Z\n"
        body += "".join(f"{k}={v}\n" for k, v in on_disk.items())
        body += extra_lines
        target.write_text(body, encoding="utf-8")

    calls = tmp_path / "calls.txt"
    script = HARNESS.format(
        step27=step27_source(),
        stdin=" ".join(f"[{k}]={v!r}".replace("'", '"') for k, v in stdin.items()),
    )
    # Written to a file rather than passed to `bash -c`. On Windows the script
    # travels through CreateProcess's command line, and this one is large enough
    # and quoted heavily enough that it arrives mangled — bash then reports a
    # syntax error in code that is perfectly valid. A file has no such transit.
    script_path = tmp_path / "harness.sh"
    script_path.write_text(script, encoding="utf-8", newline="\n")
    proc = subprocess.run(
        [BASH, str(script_path).replace("\\", "/")],
        cwd=REPO / "deploy", capture_output=True, text=True,
        env={**os.environ, "NO_COLOR": "1",
             "SENTINEL_CONFIG_DIR": str(cfg).replace("\\", "/"),
             "SENTINEL_USER": "sentinel",
             "CALLS": str(calls).replace("\\", "/")},
    )
    written = {}
    if target.exists():
        for line in target.read_text(encoding="utf-8").splitlines():
            if line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            written[k] = v
    return {"proc": proc, "keys": written,
            "calls": calls.read_text(encoding="utf-8") if calls.exists() else ""}


# ---------------------------------------------------------------------------
# Reading stdin: a line that is not a key must not be treated as one
# ---------------------------------------------------------------------------
READER = """
source ./lib/common.sh
{reader}
for k in "${{!SECRETS[@]}}"; do printf 'KEY:%s=%s\\n' "$k" "${{SECRETS[$k]}}"; done
"""


def run_reader(tmp_path: Path, stdin_text: str) -> dict:
    """The shipped stdin block — declarations, reader and its warnings."""
    text = INSTALL_SH.read_text(encoding="utf-8")
    match = re.search(r"^declare -A SECRETS=\(\).*?^fi$", text, re.S | re.M)
    assert match, "cannot find the stdin secrets block in install.sh"
    assert "read_stdin_secrets" in match.group(0)

    script = tmp_path / "reader.sh"
    script.parent.mkdir(parents=True, exist_ok=True)
    script.write_text(READER.format(reader=match.group(0)), encoding="utf-8", newline="\n")
    # Bytes, not text=True. On Windows a text-mode pipe rewrites every \n as
    # \r\n, so an LF fixture would arrive as CRLF and the two cases below could
    # not be told apart — which is how the CRLF handling went unnoticed in the
    # first place: the harness was silently feeding CRLF to everything.
    proc = subprocess.run(
        [BASH, str(script).replace("\\", "/")],
        cwd=REPO / "deploy", capture_output=True,
        input=stdin_text.encode("utf-8"), env={**os.environ, "NO_COLOR": "1"},
    )
    stdout = proc.stdout.decode("utf-8", "replace")
    stderr = proc.stderr.decode("utf-8", "replace")
    parsed = {}
    for line in stdout.split("\n"):
        if line.startswith("KEY:"):
            k, _, v = line[4:].partition("=")
            parsed[k] = v
    return {"proc": proc, "out": stdout, "err": stderr, "keys": parsed}


def test_a_wrapped_value_never_becomes_a_key_name(tmp_path):
    """The leak, in the shape that produced it.

    An editor wrapped a value in secrets/.env.local, so the second line had no
    `=`. Read with `IFS='=' read -r key value`, that line became a KEY whose
    name was the tail of an API key — and the installer printed that name when
    it declined to write it. The tail landed on the operator's console and in
    the deploy log, which is a rotated key plus an incident.

    Line numbers, never content: on a malformed line the content is the secret.
    """
    tail = "EP0jRhaJInouJPfiFesxkXVVFlGspGPcIMknQR4ww-EIZJ-QAA"
    out = run_reader(tmp_path, f"ANTHROPIC_API_KEY=sk-first-part-of-the-value\n{tail}\n")
    combined = out["out"] + out["err"]

    assert tail not in combined, "secret material printed as a key name"
    assert list(out["keys"]) == ["ANTHROPIC_API_KEY"], out["keys"]
    assert "line(s): 2" in combined, f"the line number is not reported: {combined}"


def test_the_reader_still_reads_ordinary_secrets(tmp_path):
    """The guard must not eat the normal case: values with '=' in them, quoted
    values, blank lines and comments all have to survive."""
    out = run_reader(tmp_path, "\n".join([
        "# comment",
        "   # indented comment",
        "",
        "SENTINEL_DB_PASSWORD=abc=def==",
        'TELEGRAM_BOT_TOKEN="quoted-value"',
        "  INDENTED_KEY=indented",
    ]) + "\n")
    assert out["keys"]["SENTINEL_DB_PASSWORD"] == "abc=def=="
    assert out["keys"]["TELEGRAM_BOT_TOKEN"] == "quoted-value"
    assert out["keys"]["INDENTED_KEY"] == "indented"
    assert "line(s)" not in out["err"], "a valid file produced a warning"


def test_a_crlf_file_does_not_produce_a_password_the_daemons_cannot_use(tmp_path):
    """A secrets/.env.local saved by a Windows editor.

    The CR survived into the value, which defeated the trailing-quote strip, and
    that exact string went to `ALTER ROLE ... PASSWORD` and into secrets.env —
    while sentinel/config.py strips the line when the daemons read it. So every
    daemon would authenticate with a value one byte shorter than the one the
    database was given: a rotation that reports success and leaves Sentinel
    unable to reach its own database.

    Found because this harness was itself feeding CRLF on Windows without
    anybody asking it to.
    """
    line = 'SENTINEL_DB_PASSWORD="secret"'
    lf = run_reader(tmp_path / "lf", line + chr(10))
    crlf = run_reader(tmp_path / "crlf", line + chr(13) + chr(10))
    assert lf["keys"]["SENTINEL_DB_PASSWORD"] == "secret"
    assert crlf["keys"] == lf["keys"], "CRLF and LF must yield the same secret"
    # Handled, but said out loud: the operator's editor is doing something they
    # did not ask for, and that file is not covered by .gitattributes.
    assert "CRLF" in crlf["err"]
    assert "CRLF" not in lf["err"]


# ---------------------------------------------------------------------------
# Membership has to be exact
# ---------------------------------------------------------------------------
def test_in_list_does_not_match_a_prefix(tmp_path):
    """A loose match here deletes secrets.

    `in_list` decides whether a key found on disk is already known. With prefix
    matching, a host key called SENTINEL_SESSION is judged to be
    SENTINEL_SESSION_SECRET, is never added to the write order, and disappears
    from the rewritten file — the blocker's failure mode, restored.
    """
    script = tmp_path / "inlist.sh"
    script.parent.mkdir(parents=True, exist_ok=True)
    script.write_text(
        "source ./lib/common.sh\n"
        'for probe in SENTINEL_SESSION TELEGRAM_APPLY SENTINEL_SESSION_SECRET_X \n'
        "do\n"
        '  in_list "$probe" TELEGRAM_CALLBACK_HMAC_KEY SENTINEL_SESSION_SECRET '
        'TELEGRAM_APPLY_PIN && printf "MATCHED:%s\\n" "$probe"\n'
        "done\n"
        'in_list SENTINEL_SESSION_SECRET TELEGRAM_CALLBACK_HMAC_KEY '
        'SENTINEL_SESSION_SECRET && printf "EXACT-OK\\n"\n',
        encoding="utf-8", newline="\n")
    proc = subprocess.run([BASH, str(script).replace("\\", "/")],
                          cwd=REPO / "deploy", capture_output=True, text=True,
                          env={**os.environ, "NO_COLOR": "1"})
    assert "EXACT-OK" in proc.stdout, "exact membership no longer works at all"
    assert "MATCHED" not in proc.stdout, f"a non-member matched: {proc.stdout}"


# ---------------------------------------------------------------------------
# The blocker
# ---------------------------------------------------------------------------
def test_a_rotation_run_keeps_every_key_the_host_already_had(tmp_path):
    """The reported failure: `--force-step 22,27` deleted SENTINEL_BEACON_SECRET.

    Eight keys on disk, five supplied on stdin, one of them rotated. All eight
    must survive; only the rotated one may change. Lose the beacon key and the
    external witness — the only thing that reports Sentinel's own death — goes
    silent, while every local check keeps saying the host is fine.
    """
    stdin = {k: HOST_SECRETS[k] for k in
             ("ANTHROPIC_API_KEY", "TELEGRAM_BOT_TOKEN", "TELEGRAM_CHAT_ID",
              "TELEGRAM_APPLY_PIN")}
    stdin["SENTINEL_DB_PASSWORD"] = "NEW-db-password"

    out = run_step_secrets(tmp_path, HOST_SECRETS, stdin)
    assert out["proc"].returncode == 0, out["proc"].stderr

    assert set(out["keys"]) == set(HOST_SECRETS), (
        "keys lost: " + str(sorted(set(HOST_SECRETS) - set(out["keys"]))))
    assert out["keys"]["SENTINEL_DB_PASSWORD"] == "NEW-db-password"
    for key, value in HOST_SECRETS.items():
        if key == "SENTINEL_DB_PASSWORD":
            continue
        assert out["keys"][key] == value, f"{key} changed during a DB-password rotation"


def test_the_carried_keys_are_named_in_the_output(tmp_path):
    """The operator has to be able to see that it happened.

    The step already printed a green line about the keys it kept while deleting
    another one — an accurate sentence that produced a false impression. Names
    only; a value here would be a value in the deploy log.

    The key used here has to be one the installer genuinely does not manage.
    SENTINEL_BEACON_SECRET was that key until 19 August 2026, when it joined
    OPERATOR_SECRET_KEYS and stopped being carried at all — so a test still
    naming it would have gone green on a line that no longer proves anything.
    """
    host = dict(HOST_SECRETS, A_KEY_THIS_INSTALLER_NEVER_HEARD_OF="f" * 64)
    out = run_step_secrets(tmp_path, host, {})
    assert "A_KEY_THIS_INSTALLER_NEVER_HEARD_OF" in out["proc"].stdout
    assert "f" * 64 not in out["proc"].stdout + out["proc"].stderr
    assert out["keys"]["A_KEY_THIS_INSTALLER_NEVER_HEARD_OF"] == "f" * 64
    # And the value of a key it DOES manage stays out of the log too.
    assert "c" * 64 not in out["proc"].stdout + out["proc"].stderr


def test_an_unknown_key_is_not_regenerated_but_carried(tmp_path):
    """SENTINEL_BEACON_SECRET must match the watcher's copy. A fresh value is as
    broken as no value at all, and harder to notice: the beacon would sign
    happily and the watcher would reject every beat as a bad signature."""
    out = run_step_secrets(tmp_path, HOST_SECRETS, {})
    assert out["keys"]["SENTINEL_BEACON_SECRET"] == "c" * 64
    assert "FRESHLY-GENERATED" not in out["keys"].values()
    assert "rand -hex 32" not in out["calls"], "a key was minted when all eight existed"


# ---------------------------------------------------------------------------
# The behaviour that was already right, still right
# ---------------------------------------------------------------------------
def test_only_the_generated_keys_may_be_created_from_nothing(tmp_path):
    """Minting a value for a key nobody set is worse than leaving it unset.

    TELEGRAM_APPLY_PIN is a PIN the operator types. Absent, the feature is off.
    Filled with 32 random bytes by the installer, patch apply starts demanding a
    PIN that exists nowhere except a 0640 file on the server — the operator is
    locked out of their own approval path and nothing in the run mentions it.
    Only the two host-generated keys are allowed to appear out of thin air.
    """
    on_disk = {k: v for k, v in HOST_SECRETS.items() if k != "TELEGRAM_APPLY_PIN"}
    out = run_step_secrets(tmp_path, on_disk, {})
    assert out["proc"].returncode == 0, out["proc"].stderr
    assert "TELEGRAM_APPLY_PIN" not in out["keys"], \
        f"a PIN was invented: {out['keys'].get('TELEGRAM_APPLY_PIN')!r}"
    assert "rand -hex 32" not in out["calls"]


def test_generated_keys_are_created_only_when_the_host_has_none(tmp_path):
    """A fresh host needs them; a host that has them must keep them, or every
    stored TOTP enrolment becomes undecryptable."""
    fresh = run_step_secrets(tmp_path / "a", None, {"SENTINEL_DB_PASSWORD": "x"})
    assert fresh["keys"]["SENTINEL_SESSION_SECRET"] == "FRESHLY-GENERATED"
    assert fresh["keys"]["TELEGRAM_CALLBACK_HMAC_KEY"] == "FRESHLY-GENERATED"

    again = run_step_secrets(tmp_path / "b", HOST_SECRETS, {})
    assert again["keys"]["SENTINEL_SESSION_SECRET"] == "b" * 64
    assert "rand -hex 32" not in again["calls"]


def test_an_upgrade_supplying_nothing_erases_nothing(tmp_path):
    """A re-deploy with no secrets on stdin — the documented upgrade path — must
    leave every value byte-identical."""
    out = run_step_secrets(tmp_path, HOST_SECRETS, {})
    assert out["keys"] == HOST_SECRETS


def test_the_mode_is_set_before_any_content_exists(tmp_path):
    """Writing first and chmod'ing after leaves a window in which every account
    on the host can read the file — a window that contains the API key, the bot
    token and the database password."""
    out = run_step_secrets(tmp_path, HOST_SECRETS, {})
    calls = [l for l in out["calls"].splitlines() if l.startswith("chmod")]
    assert calls, "the temp file is never chmod'ed"
    assert "0640" in calls[0], calls[0]
    assert calls[0].endswith("size=0"), f"mode set after content was written: {calls[0]}"


# ---------------------------------------------------------------------------
# Things it cannot know about
# ---------------------------------------------------------------------------
def test_a_key_only_stdin_knows_is_refused_out_loud(tmp_path):
    """A name the installer does not know is far more likely a typo in
    .env.local than a new secret, and writing it would make the typo look like a
    successful rotation. But the operator typed it on purpose, so dropping it
    silently is the same failure from the other direction.

    (This is a misuse guard, not a privilege boundary. Nothing loads secrets.env
    as an EnvironmentFile — sentinel/config.py reads it directly and looks up a
    fixed set of names. An earlier version of this docstring claimed otherwise,
    which is how a constraint nobody can check gets preserved forever.)
    """
    out = run_step_secrets(tmp_path, HOST_SECRETS,
                           {"LD_PRELOAD": "/tmp/evil.so", "SENTINEL_DB_PASSWORD": "NEW"})
    assert "LD_PRELOAD" not in out["keys"]
    assert "LD_PRELOAD" in out["proc"].stderr
    assert out["keys"]["SENTINEL_DB_PASSWORD"] == "NEW"


def test_a_key_already_on_the_host_may_be_updated_from_stdin(tmp_path):
    """The refusal above is about names, not about values: a name the host
    already has was put there by root, so rotating it through the deploy channel
    is allowed. Otherwise the beacon key could never be rotated at all, and the
    installer would ignore a value the operator explicitly supplied."""
    out = run_step_secrets(tmp_path, HOST_SECRETS,
                           {"SENTINEL_BEACON_SECRET": "d" * 64})
    assert out["keys"]["SENTINEL_BEACON_SECRET"] == "d" * 64


def test_a_shared_key_lands_on_a_host_that_never_had_it(tmp_path):
    """The failure this prevents: a second server is installed, the operator
    supplies SENTINEL_SHIP_SECRET through the deploy channel, and the installer
    drops it as an unknown name. Everything reports success -- the unit is
    enabled, the process starts, and `ship` exits 0 when the secret is missing
    -- so the only symptom is a panel that never gains that instance's data,
    discovered whenever somebody happens to look.

    HOST_SECRETS has no ship key, so this is the FIRST placement, not a
    rotation. That is the case the carry-forward rule cannot cover, because
    there is nothing yet to carry."""
    out = run_step_secrets(tmp_path, HOST_SECRETS,
                           {"SENTINEL_SHIP_SECRET": "e" * 64})
    assert out["keys"]["SENTINEL_SHIP_SECRET"] == "e" * 64, (
        "the ship key was dropped as an unknown name; a new host cannot be "
        "given one through the reviewed path")
    assert "SENTINEL_SHIP_SECRET" not in out["proc"].stderr, (
        "the key landed but was also reported as refused")
    # The keys already on the host are untouched by the new name.
    assert out["keys"]["SENTINEL_BEACON_SECRET"] == "c" * 64
    assert out["keys"]["SENTINEL_SESSION_SECRET"] == "b" * 64


def test_a_shared_key_nobody_supplied_is_not_written_empty(tmp_path):
    """Adding names to OPERATOR_SECRET_KEYS must not create empty lines.

    `sentinel/config.py:load_secrets` reads this file directly. A line
    `SENTINEL_SHIP_SECRET=` is a key that EXISTS with no value, which reads as
    configured-but-broken rather than absent -- and the two get different
    diagnoses from anyone reading the file."""
    out = run_step_secrets(tmp_path, HOST_SECRETS, {})
    assert "SENTINEL_SHIP_SECRET" not in out["keys"], (
        "a key nobody supplied was written anyway")
    body = (tmp_path / "etc" / "secrets.env").read_text(encoding="utf-8")
    assert "SENTINEL_SHIP_SECRET=" not in body


def test_a_malformed_name_is_never_printed_even_if_it_reaches_this_step(tmp_path):
    """The second lock on the door the stdin reader now closes.

    The refusal message prints the key name. If anything ever puts a malformed
    "name" into SECRETS again — which is exactly what reading with IFS='=' did
    to a wrapped value — that message would publish secret material. The name is
    only printed once it looks like a name.
    """
    tail = "EP0jRhaJInouJPfiFesxkXVVFlGspGPcIMknQR4ww-EIZJ-QAA"
    out = run_step_secrets(tmp_path, HOST_SECRETS, {tail: ""})
    combined = out["proc"].stdout + out["proc"].stderr
    assert tail not in combined, "a malformed key name was printed verbatim"
    assert "withheld" in combined, "the refusal is not reported at all"


def test_a_carried_key_with_an_empty_value_is_kept_not_just_counted(tmp_path):
    """Reporting a key as carried and then dropping it is intent-as-effect.

    The green line named it; the value was empty, so the write was skipped, and
    the key vanished. It also makes the key-name diff in OPERARE.md §11 (a) —
    the check that proves nothing was lost — report a loss on a healthy run.
    """
    on_disk = dict(HOST_SECRETS, AN_UNKNOWN_KEY_ON_DISK="")
    out = run_step_secrets(tmp_path, on_disk, {})
    assert out["proc"].returncode == 0, out["proc"].stderr
    assert "AN_UNKNOWN_KEY_ON_DISK" in out["proc"].stdout, "not even reported"
    assert "AN_UNKNOWN_KEY_ON_DISK" in out["keys"], \
        "named as carried over, then dropped from the file"
    assert set(out["keys"]) == set(on_disk)


def test_an_indented_comment_is_a_comment(tmp_path):
    """`   # notă` triggered "recover them from a backup if they mattered" — a
    warning that must only ever mean "you lost a secret". Cry wolf once and the
    real one is read as the same noise."""
    out = run_step_secrets(tmp_path, HOST_SECRETS, {},
                           extra_lines="   # o notă a operatorului\n")
    combined = out["proc"].stdout + out["proc"].stderr
    assert "backup" not in combined, combined
    assert set(out["keys"]) == set(HOST_SECRETS)


def test_an_indented_key_keeps_its_value(tmp_path):
    """sentinel/config.py strips before parsing, so an indented key WORKS today.

    The installer must therefore read it the same way. If the scan accepts the
    key but the value lookup does not, the key survives with an empty value —
    a deletion that passes the key-name diff, which is the worst kind.
    """
    out = run_step_secrets(tmp_path, HOST_SECRETS, {},
                           extra_lines="  INDENTED_KEY=indented-value\n")
    assert out["keys"].get("INDENTED_KEY") == "indented-value"


def test_an_unparseable_line_is_reported_by_line_number(tmp_path):
    """It cannot be carried over, so it has to be announced. The old file is
    replaced; an operator who is not told loses whatever was on that line
    without ever learning it existed. The number, never the content — this file
    is nothing but secrets."""
    out = run_step_secrets(tmp_path, HOST_SECRETS, {},
                           extra_lines="this line is not KEY=value\n")
    combined = out["proc"].stdout + out["proc"].stderr
    assert "10" in combined and "line" in combined.lower()
    assert "this line is not" not in combined
